version: '3.8'

services:
  db:
    image: postgres
    restart: always
    container_name: db-bsm-postgres
    environment:
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: postgress123
      POSTGRES_DB: bsm
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - my-network
  bsm:
    restart: always
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bsm
      SPRING_DATASOURCE_USERNAME: postgress
      SPRING_DATASOURCE_PASSWORD: postgress123
    networks:
      - my-network
volumes:
  db_data:
networks:
  my-network: